- name: Create job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/.xml')test.xml }}"
    name: test
    password: admin123
    url: http://172.31.2.169:8080
    user: admin
#  loop:
#    - { name: "ci-pipelines"}


#- name: Include Multi Branch task file
#  ansible.builtin.include_tasks: mbranch.yml
#  loop:
#    - { name: "cart"}
#    - { name: "catalogue"}
#    - { name: "user"}
#    - { name: "shipping"}
#    - { name: "payment"}
#    - { name: "frontend"}